### ISSUE TITLE
Support for async/Promises

### ISSUE THREAD

**Issue by i404788** [reearth/quickjs-emscripten-sync#3]
Hey there,

I've had a blast using your library but noticed promises don't really work (resolving them inside QuickJS). Is there a limitation on this, or is it possible to use them?

Thanks

Error for reference: `TypeError: Promise.prototype.then called on incompatible Proxy`

**Comment by justjake** [comment]
I can’t follow what “depromisify” means, but maybe this can help: In the base library, I recently added [QuickJSVm.resolvePromise](https://github.com/justjake/quickjs-emscripten/blob/master/doc/classes/quickjsvm.md#resolvepromise) which turns a VM promise into a host promise. This was the missing dual to [QuickJSVm.newPromise](https://github.com/justjake/quickjs-emscripten/blob/master/doc/classes/quickjsvm.md#newpromise), which is how the host can construct a promise inside the guest. 

The error path makes promise handling tricky - if a VM promise rejection is unmarshalled to a host promise rejection, the unmarshalling layer must be sure to free the rejection reason handle to avoid a leak. For this reason QuickJSVm.resolvePromise always resolves with a result object (and never rejects) to ensure the developer must consider the error handle.

**Comment by i404788** [comment]
The depromisify function is specifically for the sync library, it will warp/proxy classes/functions (and classes' prototypes) such that the last argument will become a callback, and no Promise is returned unless no callback is added. This is the inverse functionality of the shim function `promisify`.

I think it would be a lot better to use proper quickjs Promise handling though, since depromisify does make callback hell very common and it has some edge-cases due to the way it detects arguments.

**Comment by atifsyedali** [comment]
Any updates?

**Comment by Matthiee** [comment]
Would be nice to have this feature! 👍

**Comment by rot1024** [comment]
Supported. Check it!
